# Generated by Django 5.0.1 on 2026-01-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenance",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="completion_date",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="issue_description",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="scheduled_date",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="status",
        ),
        migrations.AddField(
            model_name="maintenance",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="report_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="representative",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="machine_name",
            field=models.CharField(default="Monthly Maintenance", max_length=200),
        ),
    ]
