# Generated by Django 5.0.1 on 2026-01-02 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("company", models.CharField(max_length=200)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("MEETING", "Meeting"),
                            ("TRAINING", "Training"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SITE_VISIT", "Site Visit"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("check_in", models.DateTimeField(auto_now_add=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in"],
            },
        ),
    ]
