# Generated by Django 5.0.1 on 2026-01-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
