# Generated by Django 5.0.1 on 2026-01-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0002_alter_visitor_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="categories",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="industry_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="photograph_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
