# Generated by Django 5.0.1 on 2026-05-06 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0003_visitor_categories_visitor_industry_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="check_in",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("MEETING", "Meeting"),
                    ("TRAINING", "Training"),
                    ("MAINTENANCE", "Maintenance"),
                    ("SITE_VISIT", "Site Visit"),
                    ("INDUSTRIAL", "Industrial"),
                    ("ACADEMIC", "Academic"),
                    ("GOVERNMENT", "Government"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
