# Generated by Django 5.0.1 on 2026-01-02 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical"),
                            ("SAFETY", "Safety"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("COMPLIANCE", "Compliance"),
                            ("OTHER", "Other"),
                        ],
                        default="TECHNICAL",
                        max_length=50,
                    ),
                ),
                ("trainer_name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("attendees_count", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
